/*******************************************************************************
* Copyright (c) 2020 Analog Devices, Inc. All Rights Reserved.
* This software is proprietary and confidential to Analog Devices, Inc. and its licensors.
*******************************************************************************/

#ifndef ADI_BMS_DEFS_H_
#define ADI_BMS_DEFS_H_

#include <stdint.h>
#include "wb_crc_16.h"
#include "wb_crc_config.h"


// Container File Information
#define ADI_BMS_REVISION                                          22u
#define ADI_BMS_CONTAINERID                                       0u
#define ADI_BMS_VERSION                                           1u
#define ADI_BMS_DEVICEID                                          134u
#define ADI_BMS_DEVICEVERSION                                     2u
#define ADI_BMS_SPICLOCKRATE                                      2000u
#define ADI_BMS_INITSCRIPT_ID                                     1u
#define ADI_BMS_MONITORSCRIPT_ID                                  255u
#define ADI_BMS_BASESCRIPT_ID                                     2u
#define ADI_BMS_NUMOFSCRIPTS                                      4u
#define ADI_BMS_MONITORALGTABLEOFFSET                             65535u
#define ADI_BMS_TOTALCONTAINERLENGTH                              2988u
#define ADI_BMS_CONTAINER_FILE_CRC                                0xCE80687Bu

#define ADI_BMS_PACKET_CRC_POLY                                   WB_CRC16_POLY
#define ADI_BMS_PACKET_CRC_SEED                                   WB_CRC_SEED

// Script Information: init
#define ADI_BMS_INIT_ID                                           1u
#define ADI_BMS_INIT_PKT_0_ID                                     0u
#define ADI_BMS_INIT_PKT_1_ID                                     1u
#define ADI_BMS_INIT_PKT_2_ID                                     2u

#define ADI_BMS_INIT_CMD_0_EMPTY_OFFSET                           5u
#define ADI_BMS_INIT_CMD_0_EMPTY_LENGTH                           0u
#define ADI_BMS_INIT_CMD_0_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_1_WRCFGA_OFFSET                          12u
#define ADI_BMS_INIT_CMD_1_WRCFGA_LENGTH                          8u
#define ADI_BMS_INIT_CMD_1_ENTRY_DATA_LENGTH                      8u
#define ADI_BMS_INIT_CMD_2_EMPTY_OFFSET                           25u
#define ADI_BMS_INIT_CMD_2_EMPTY_LENGTH                           0u
#define ADI_BMS_INIT_CMD_2_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_3_CLRCELL_OFFSET                         32u
#define ADI_BMS_INIT_CMD_3_CLRCELL_LENGTH                         0u
#define ADI_BMS_INIT_CMD_3_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_4_CLRFC_OFFSET                           39u
#define ADI_BMS_INIT_CMD_4_CLRFC_LENGTH                           0u
#define ADI_BMS_INIT_CMD_4_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_5_CLRAUX_OFFSET                          46u
#define ADI_BMS_INIT_CMD_5_CLRAUX_LENGTH                          0u
#define ADI_BMS_INIT_CMD_5_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_6_CLRSPIN_OFFSET                         53u
#define ADI_BMS_INIT_CMD_6_CLRSPIN_LENGTH                         0u
#define ADI_BMS_INIT_CMD_6_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_7_CLRFLAG_OFFSET                         60u
#define ADI_BMS_INIT_CMD_7_CLRFLAG_LENGTH                         8u
#define ADI_BMS_INIT_CMD_7_ENTRY_DATA_LENGTH                      8u
#define ADI_BMS_INIT_CMD_8_MUTE_OFFSET                            75u
#define ADI_BMS_INIT_CMD_8_MUTE_LENGTH                            0u
#define ADI_BMS_INIT_CMD_8_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_9_ADAX_OFFSET                            82u
#define ADI_BMS_INIT_CMD_9_ADAX_LENGTH                            0u
#define ADI_BMS_INIT_CMD_9_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_INIT_CMD_10_ADCV_OFFSET                           89u
#define ADI_BMS_INIT_CMD_10_ADCV_LENGTH                           0u
#define ADI_BMS_INIT_CMD_10_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_INIT_CMD_11_EMPTY_OFFSET                          94u
#define ADI_BMS_INIT_CMD_11_EMPTY_LENGTH                          0u
#define ADI_BMS_INIT_CMD_11_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_INIT_CMD_12_UNMUTE_OFFSET                         101u
#define ADI_BMS_INIT_CMD_12_UNMUTE_LENGTH                         0u
#define ADI_BMS_INIT_CMD_12_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_INIT_CMD_13_RDACA_OFFSET                          108u
#define ADI_BMS_INIT_CMD_13_RDACA_LENGTH                          8u
#define ADI_BMS_INIT_CMD_13_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_14_RDACB_OFFSET                          123u
#define ADI_BMS_INIT_CMD_14_RDACB_LENGTH                          8u
#define ADI_BMS_INIT_CMD_14_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_15_RDACC_OFFSET                          138u
#define ADI_BMS_INIT_CMD_15_RDACC_LENGTH                          8u
#define ADI_BMS_INIT_CMD_15_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_16_RDACD_OFFSET                          153u
#define ADI_BMS_INIT_CMD_16_RDACD_LENGTH                          8u
#define ADI_BMS_INIT_CMD_16_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_17_RDACE_OFFSET                          168u
#define ADI_BMS_INIT_CMD_17_RDACE_LENGTH                          8u
#define ADI_BMS_INIT_CMD_17_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_18_RDACF_OFFSET                          183u
#define ADI_BMS_INIT_CMD_18_RDACF_LENGTH                          8u
#define ADI_BMS_INIT_CMD_18_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_19_RDAUXA_OFFSET                         198u
#define ADI_BMS_INIT_CMD_19_RDAUXA_LENGTH                         8u
#define ADI_BMS_INIT_CMD_19_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_20_RDAUXE_OFFSET                         213u
#define ADI_BMS_INIT_CMD_20_RDAUXE_LENGTH                         8u
#define ADI_BMS_INIT_CMD_20_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_21_RDSTATC_OFFSET                        228u
#define ADI_BMS_INIT_CMD_21_RDSTATC_LENGTH                        8u
#define ADI_BMS_INIT_CMD_21_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_22_RDACA_OFFSET                          243u
#define ADI_BMS_INIT_CMD_22_RDACA_LENGTH                          8u
#define ADI_BMS_INIT_CMD_22_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_23_RDACB_OFFSET                          258u
#define ADI_BMS_INIT_CMD_23_RDACB_LENGTH                          8u
#define ADI_BMS_INIT_CMD_23_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_24_RDACC_OFFSET                          273u
#define ADI_BMS_INIT_CMD_24_RDACC_LENGTH                          8u
#define ADI_BMS_INIT_CMD_24_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_25_RDACD_OFFSET                          288u
#define ADI_BMS_INIT_CMD_25_RDACD_LENGTH                          8u
#define ADI_BMS_INIT_CMD_25_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_26_RDACE_OFFSET                          303u
#define ADI_BMS_INIT_CMD_26_RDACE_LENGTH                          8u
#define ADI_BMS_INIT_CMD_26_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_27_RDACF_OFFSET                          318u
#define ADI_BMS_INIT_CMD_27_RDACF_LENGTH                          8u
#define ADI_BMS_INIT_CMD_27_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_28_RDAUXA_OFFSET                         333u
#define ADI_BMS_INIT_CMD_28_RDAUXA_LENGTH                         8u
#define ADI_BMS_INIT_CMD_28_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_29_RDAUXE_OFFSET                         348u
#define ADI_BMS_INIT_CMD_29_RDAUXE_LENGTH                         8u
#define ADI_BMS_INIT_CMD_29_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_30_RDSTATC_OFFSET                        363u
#define ADI_BMS_INIT_CMD_30_RDSTATC_LENGTH                        8u
#define ADI_BMS_INIT_CMD_30_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_31_RDACA_OFFSET                          378u
#define ADI_BMS_INIT_CMD_31_RDACA_LENGTH                          8u
#define ADI_BMS_INIT_CMD_31_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_32_RDACB_OFFSET                          393u
#define ADI_BMS_INIT_CMD_32_RDACB_LENGTH                          8u
#define ADI_BMS_INIT_CMD_32_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_33_RDACC_OFFSET                          408u
#define ADI_BMS_INIT_CMD_33_RDACC_LENGTH                          8u
#define ADI_BMS_INIT_CMD_33_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_34_RDACD_OFFSET                          423u
#define ADI_BMS_INIT_CMD_34_RDACD_LENGTH                          8u
#define ADI_BMS_INIT_CMD_34_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_35_RDACE_OFFSET                          438u
#define ADI_BMS_INIT_CMD_35_RDACE_LENGTH                          8u
#define ADI_BMS_INIT_CMD_35_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_36_RDACF_OFFSET                          453u
#define ADI_BMS_INIT_CMD_36_RDACF_LENGTH                          8u
#define ADI_BMS_INIT_CMD_36_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_37_RDAUXA_OFFSET                         468u
#define ADI_BMS_INIT_CMD_37_RDAUXA_LENGTH                         8u
#define ADI_BMS_INIT_CMD_37_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_38_RDAUXE_OFFSET                         483u
#define ADI_BMS_INIT_CMD_38_RDAUXE_LENGTH                         8u
#define ADI_BMS_INIT_CMD_38_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_INIT_CMD_39_RDSTATC_OFFSET                        498u
#define ADI_BMS_INIT_CMD_39_RDSTATC_LENGTH                        8u
#define ADI_BMS_INIT_CMD_39_ENTRY_DATA_LENGTH                     8u

// Script Information: base
#define ADI_BMS_BASE_ID                                           2u
#define ADI_BMS_BASE_PKT_0_ID                                     3u
#define ADI_BMS_BASE_PKT_1_ID                                     4u
#define ADI_BMS_BASE_PKT_2_ID                                     5u

#define ADI_BMS_BASE_CMD_0_EMPTY_OFFSET                           5u
#define ADI_BMS_BASE_CMD_0_EMPTY_LENGTH                           0u
#define ADI_BMS_BASE_CMD_0_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_1_CLRCELL_OFFSET                         12u
#define ADI_BMS_BASE_CMD_1_CLRCELL_LENGTH                         0u
#define ADI_BMS_BASE_CMD_1_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_2_CLRFC_OFFSET                           19u
#define ADI_BMS_BASE_CMD_2_CLRFC_LENGTH                           0u
#define ADI_BMS_BASE_CMD_2_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_3_CLRAUX_OFFSET                          26u
#define ADI_BMS_BASE_CMD_3_CLRAUX_LENGTH                          0u
#define ADI_BMS_BASE_CMD_3_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_4_CLRSPIN_OFFSET                         33u
#define ADI_BMS_BASE_CMD_4_CLRSPIN_LENGTH                         0u
#define ADI_BMS_BASE_CMD_4_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_5_CLROUV_OFFSET                          40u
#define ADI_BMS_BASE_CMD_5_CLROUV_LENGTH                          8u
#define ADI_BMS_BASE_CMD_5_ENTRY_DATA_LENGTH                      8u
#define ADI_BMS_BASE_CMD_6_CLRFLAG_OFFSET                         55u
#define ADI_BMS_BASE_CMD_6_CLRFLAG_LENGTH                         8u
#define ADI_BMS_BASE_CMD_6_ENTRY_DATA_LENGTH                      8u
#define ADI_BMS_BASE_CMD_7_MUTE_OFFSET                            70u
#define ADI_BMS_BASE_CMD_7_MUTE_LENGTH                            0u
#define ADI_BMS_BASE_CMD_7_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_8_ADAX_OFFSET                            77u
#define ADI_BMS_BASE_CMD_8_ADAX_LENGTH                            0u
#define ADI_BMS_BASE_CMD_8_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_9_ADAX2_OFFSET                           84u
#define ADI_BMS_BASE_CMD_9_ADAX2_LENGTH                           0u
#define ADI_BMS_BASE_CMD_9_ENTRY_DATA_LENGTH                      0u
#define ADI_BMS_BASE_CMD_10_ADCV_OFFSET                           91u
#define ADI_BMS_BASE_CMD_10_ADCV_LENGTH                           0u
#define ADI_BMS_BASE_CMD_10_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_11_EMPTY_OFFSET                          96u
#define ADI_BMS_BASE_CMD_11_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_11_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_12_UNMUTE_OFFSET                         103u
#define ADI_BMS_BASE_CMD_12_UNMUTE_LENGTH                         0u
#define ADI_BMS_BASE_CMD_12_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_13_RDACA_OFFSET                          110u
#define ADI_BMS_BASE_CMD_13_RDACA_LENGTH                          8u
#define ADI_BMS_BASE_CMD_13_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_14_RDACB_OFFSET                          125u
#define ADI_BMS_BASE_CMD_14_RDACB_LENGTH                          8u
#define ADI_BMS_BASE_CMD_14_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_15_RDACC_OFFSET                          140u
#define ADI_BMS_BASE_CMD_15_RDACC_LENGTH                          8u
#define ADI_BMS_BASE_CMD_15_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_16_RDACD_OFFSET                          155u
#define ADI_BMS_BASE_CMD_16_RDACD_LENGTH                          8u
#define ADI_BMS_BASE_CMD_16_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_17_RDACE_OFFSET                          170u
#define ADI_BMS_BASE_CMD_17_RDACE_LENGTH                          8u
#define ADI_BMS_BASE_CMD_17_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_18_RDACF_OFFSET                          185u
#define ADI_BMS_BASE_CMD_18_RDACF_LENGTH                          8u
#define ADI_BMS_BASE_CMD_18_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_19_RDAUXA_OFFSET                         200u
#define ADI_BMS_BASE_CMD_19_RDAUXA_LENGTH                         8u
#define ADI_BMS_BASE_CMD_19_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_20_RDAUXE_OFFSET                         215u
#define ADI_BMS_BASE_CMD_20_RDAUXE_LENGTH                         8u
#define ADI_BMS_BASE_CMD_20_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_21_RDAUXD_OFFSET                         230u
#define ADI_BMS_BASE_CMD_21_RDAUXD_LENGTH                         8u
#define ADI_BMS_BASE_CMD_21_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_22_EMPTY_OFFSET                          243u
#define ADI_BMS_BASE_CMD_22_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_22_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_23_MUTE_OFFSET                           250u
#define ADI_BMS_BASE_CMD_23_MUTE_LENGTH                           0u
#define ADI_BMS_BASE_CMD_23_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_24_CLRSPIN_OFFSET                        257u
#define ADI_BMS_BASE_CMD_24_CLRSPIN_LENGTH                        0u
#define ADI_BMS_BASE_CMD_24_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_25_ADSV_OFFSET                           264u
#define ADI_BMS_BASE_CMD_25_ADSV_LENGTH                           0u
#define ADI_BMS_BASE_CMD_25_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_26_EMPTY_OFFSET                          269u
#define ADI_BMS_BASE_CMD_26_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_26_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_27_UNMUTE_OFFSET                         276u
#define ADI_BMS_BASE_CMD_27_UNMUTE_LENGTH                         0u
#define ADI_BMS_BASE_CMD_27_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_28_RDSVA_OFFSET                          283u
#define ADI_BMS_BASE_CMD_28_RDSVA_LENGTH                          8u
#define ADI_BMS_BASE_CMD_28_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_29_RDSVB_OFFSET                          298u
#define ADI_BMS_BASE_CMD_29_RDSVB_LENGTH                          8u
#define ADI_BMS_BASE_CMD_29_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_30_RDSVC_OFFSET                          313u
#define ADI_BMS_BASE_CMD_30_RDSVC_LENGTH                          8u
#define ADI_BMS_BASE_CMD_30_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_31_RDSVD_OFFSET                          328u
#define ADI_BMS_BASE_CMD_31_RDSVD_LENGTH                          8u
#define ADI_BMS_BASE_CMD_31_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_32_RDSVE_OFFSET                          343u
#define ADI_BMS_BASE_CMD_32_RDSVE_LENGTH                          8u
#define ADI_BMS_BASE_CMD_32_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_33_RDSVF_OFFSET                          358u
#define ADI_BMS_BASE_CMD_33_RDSVF_LENGTH                          8u
#define ADI_BMS_BASE_CMD_33_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_34_MUTE_OFFSET                           373u
#define ADI_BMS_BASE_CMD_34_MUTE_LENGTH                           0u
#define ADI_BMS_BASE_CMD_34_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_35_CLRSPIN_OFFSET                        380u
#define ADI_BMS_BASE_CMD_35_CLRSPIN_LENGTH                        0u
#define ADI_BMS_BASE_CMD_35_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_36_ADSV_OFFSET                           387u
#define ADI_BMS_BASE_CMD_36_ADSV_LENGTH                           0u
#define ADI_BMS_BASE_CMD_36_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_37_EMPTY_OFFSET                          392u
#define ADI_BMS_BASE_CMD_37_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_37_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_38_UNMUTE_OFFSET                         399u
#define ADI_BMS_BASE_CMD_38_UNMUTE_LENGTH                         0u
#define ADI_BMS_BASE_CMD_38_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_39_WRCFGA_OFFSET                         406u
#define ADI_BMS_BASE_CMD_39_WRCFGA_LENGTH                         8u
#define ADI_BMS_BASE_CMD_39_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_40_WRCFGB_OFFSET                         421u
#define ADI_BMS_BASE_CMD_40_WRCFGB_LENGTH                         8u
#define ADI_BMS_BASE_CMD_40_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_41_RDCFGA_OFFSET                         436u
#define ADI_BMS_BASE_CMD_41_RDCFGA_LENGTH                         8u
#define ADI_BMS_BASE_CMD_41_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_42_RDCFGB_OFFSET                         451u
#define ADI_BMS_BASE_CMD_42_RDCFGB_LENGTH                         8u
#define ADI_BMS_BASE_CMD_42_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_43_RDSTATA_OFFSET                        466u
#define ADI_BMS_BASE_CMD_43_RDSTATA_LENGTH                        8u
#define ADI_BMS_BASE_CMD_43_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_44_RDSTATB_OFFSET                        481u
#define ADI_BMS_BASE_CMD_44_RDSTATB_LENGTH                        8u
#define ADI_BMS_BASE_CMD_44_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_45_RDSTATC_OFFSET                        496u
#define ADI_BMS_BASE_CMD_45_RDSTATC_LENGTH                        8u
#define ADI_BMS_BASE_CMD_45_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_46_EMPTY_OFFSET                          509u
#define ADI_BMS_BASE_CMD_46_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_46_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_47_EMPTY_OFFSET                          514u
#define ADI_BMS_BASE_CMD_47_EMPTY_LENGTH                          0u
#define ADI_BMS_BASE_CMD_47_ENTRY_DATA_LENGTH                     0u
#define ADI_BMS_BASE_CMD_48_RDRAXA_OFFSET                         521u
#define ADI_BMS_BASE_CMD_48_RDRAXA_LENGTH                         8u
#define ADI_BMS_BASE_CMD_48_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_49_RDRAXD_OFFSET                         536u
#define ADI_BMS_BASE_CMD_49_RDRAXD_LENGTH                         8u
#define ADI_BMS_BASE_CMD_49_ENTRY_DATA_LENGTH                     8u
#define ADI_BMS_BASE_CMD_50_CLRFLAG_OFFSET                        551u
#define ADI_BMS_BASE_CMD_50_CLRFLAG_LENGTH                        8u
#define ADI_BMS_BASE_CMD_50_ENTRY_DATA_LENGTH                     8u

// Script Information: latent0
#define ADI_BMS_LATENT0_ID                                        3u
#define ADI_BMS_LATENT0_PKT_0_ID                                  6u
#define ADI_BMS_LATENT0_PKT_1_ID                                  7u
#define ADI_BMS_LATENT0_PKT_2_ID                                  8u

#define ADI_BMS_LATENT0_CMD_0_WRCFGA_OFFSET                       7u
#define ADI_BMS_LATENT0_CMD_0_WRCFGA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_0_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_1_ADCV_OFFSET                         22u
#define ADI_BMS_LATENT0_CMD_1_ADCV_LENGTH                         0u
#define ADI_BMS_LATENT0_CMD_1_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT0_CMD_2_RDSTATC_OFFSET                      29u
#define ADI_BMS_LATENT0_CMD_2_RDSTATC_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_2_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_3_WRCFGA_OFFSET                       44u
#define ADI_BMS_LATENT0_CMD_3_WRCFGA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_3_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_4_CLRFLAG_OFFSET                      59u
#define ADI_BMS_LATENT0_CMD_4_CLRFLAG_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_4_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_5_WRCFGA_OFFSET                       74u
#define ADI_BMS_LATENT0_CMD_5_WRCFGA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_5_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_6_ADCV_OFFSET                         89u
#define ADI_BMS_LATENT0_CMD_6_ADCV_LENGTH                         0u
#define ADI_BMS_LATENT0_CMD_6_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT0_CMD_7_RDSTATC_OFFSET                      96u
#define ADI_BMS_LATENT0_CMD_7_RDSTATC_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_7_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_8_WRCFGA_OFFSET                       111u
#define ADI_BMS_LATENT0_CMD_8_WRCFGA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_8_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_9_CLRFLAG_OFFSET                      126u
#define ADI_BMS_LATENT0_CMD_9_CLRFLAG_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_9_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT0_CMD_10_WRCFGA_OFFSET                      141u
#define ADI_BMS_LATENT0_CMD_10_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_10_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_11_ADCV_OFFSET                        156u
#define ADI_BMS_LATENT0_CMD_11_ADCV_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_11_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_12_EMPTY_OFFSET                       161u
#define ADI_BMS_LATENT0_CMD_12_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_12_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_13_RDSTATC_OFFSET                     168u
#define ADI_BMS_LATENT0_CMD_13_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_13_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_14_WRCFGA_OFFSET                      183u
#define ADI_BMS_LATENT0_CMD_14_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_14_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_15_CLRFLAG_OFFSET                     198u
#define ADI_BMS_LATENT0_CMD_15_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_15_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_16_WRCFGA_OFFSET                      213u
#define ADI_BMS_LATENT0_CMD_16_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_16_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_17_ADCV_OFFSET                        228u
#define ADI_BMS_LATENT0_CMD_17_ADCV_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_17_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_18_RDSTATC_OFFSET                     235u
#define ADI_BMS_LATENT0_CMD_18_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_18_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_19_WRCFGA_OFFSET                      250u
#define ADI_BMS_LATENT0_CMD_19_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_19_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_20_CLRFLAG_OFFSET                     265u
#define ADI_BMS_LATENT0_CMD_20_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_20_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_21_WRCFGA_OFFSET                      280u
#define ADI_BMS_LATENT0_CMD_21_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_21_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_22_RDSTATC_OFFSET                     295u
#define ADI_BMS_LATENT0_CMD_22_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_22_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_23_WRCFGA_OFFSET                      310u
#define ADI_BMS_LATENT0_CMD_23_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_23_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_24_CLRFLAG_OFFSET                     325u
#define ADI_BMS_LATENT0_CMD_24_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_24_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_25_WRCFGA_OFFSET                      340u
#define ADI_BMS_LATENT0_CMD_25_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_25_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_26_RDSTATC_OFFSET                     355u
#define ADI_BMS_LATENT0_CMD_26_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_26_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_27_WRCFGA_OFFSET                      370u
#define ADI_BMS_LATENT0_CMD_27_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_27_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_28_CLRFLAG_OFFSET                     385u
#define ADI_BMS_LATENT0_CMD_28_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_28_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_29_WRCFGA_OFFSET                      400u
#define ADI_BMS_LATENT0_CMD_29_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_29_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_30_RDSTATC_OFFSET                     415u
#define ADI_BMS_LATENT0_CMD_30_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_30_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_31_WRCFGA_OFFSET                      430u
#define ADI_BMS_LATENT0_CMD_31_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_31_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_32_CLRFLAG_OFFSET                     445u
#define ADI_BMS_LATENT0_CMD_32_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_32_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_33_RSTCC_OFFSET                       460u
#define ADI_BMS_LATENT0_CMD_33_RSTCC_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_33_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_34_MUTE_OFFSET                        467u
#define ADI_BMS_LATENT0_CMD_34_MUTE_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_34_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_35_WRPWMA_OFFSET                      474u
#define ADI_BMS_LATENT0_CMD_35_WRPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_35_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_36_RDPWMA_OFFSET                      489u
#define ADI_BMS_LATENT0_CMD_36_RDPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_36_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_37_WRPWMA_OFFSET                      504u
#define ADI_BMS_LATENT0_CMD_37_WRPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_37_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_38_RDPWMA_OFFSET                      519u
#define ADI_BMS_LATENT0_CMD_38_RDPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_38_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_39_WRPWMA_OFFSET                      534u
#define ADI_BMS_LATENT0_CMD_39_WRPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_39_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_40_RDPWMA_OFFSET                      549u
#define ADI_BMS_LATENT0_CMD_40_RDPWMA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_40_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_41_RDSTATC_OFFSET                     564u
#define ADI_BMS_LATENT0_CMD_41_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_41_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_42_UNMUTE_OFFSET                      579u
#define ADI_BMS_LATENT0_CMD_42_UNMUTE_LENGTH                      0u
#define ADI_BMS_LATENT0_CMD_42_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_43_CLRFLAG_OFFSET                     586u
#define ADI_BMS_LATENT0_CMD_43_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_43_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_44_WRCFGA_OFFSET                      601u
#define ADI_BMS_LATENT0_CMD_44_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_44_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_45_CLRAUX_OFFSET                      616u
#define ADI_BMS_LATENT0_CMD_45_CLRAUX_LENGTH                      0u
#define ADI_BMS_LATENT0_CMD_45_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_46_ADAX_OFFSET                        623u
#define ADI_BMS_LATENT0_CMD_46_ADAX_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_46_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_47_RDAUXD_OFFSET                      630u
#define ADI_BMS_LATENT0_CMD_47_RDAUXD_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_47_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_48_CLRFLAG_OFFSET                     645u
#define ADI_BMS_LATENT0_CMD_48_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_48_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_49_EMPTY_OFFSET                       658u
#define ADI_BMS_LATENT0_CMD_49_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_49_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_50_RDSID_OFFSET                       665u
#define ADI_BMS_LATENT0_CMD_50_RDSID_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_50_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_51_CLRFLAG_OFFSET                     680u
#define ADI_BMS_LATENT0_CMD_51_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_51_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_52_WRCFGA_OFFSET                      695u
#define ADI_BMS_LATENT0_CMD_52_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_52_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_53_EMPTY_OFFSET                       708u
#define ADI_BMS_LATENT0_CMD_53_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_53_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_54_RDSTATC_OFFSET                     715u
#define ADI_BMS_LATENT0_CMD_54_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_54_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_55_CLRFLAG_OFFSET                     730u
#define ADI_BMS_LATENT0_CMD_55_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_55_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_56_EMPTY_OFFSET                       743u
#define ADI_BMS_LATENT0_CMD_56_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_56_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_57_ADCV_OFFSET                        750u
#define ADI_BMS_LATENT0_CMD_57_ADCV_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_57_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_58_ADSV_OFFSET                        757u
#define ADI_BMS_LATENT0_CMD_58_ADSV_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_58_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_59_EMPTY_OFFSET                       762u
#define ADI_BMS_LATENT0_CMD_59_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_59_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_60_RDACA_OFFSET                       769u
#define ADI_BMS_LATENT0_CMD_60_RDACA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_60_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_61_RDACB_OFFSET                       784u
#define ADI_BMS_LATENT0_CMD_61_RDACB_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_61_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_62_RDACC_OFFSET                       799u
#define ADI_BMS_LATENT0_CMD_62_RDACC_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_62_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_63_RDACD_OFFSET                       814u
#define ADI_BMS_LATENT0_CMD_63_RDACD_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_63_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_64_RDACE_OFFSET                       829u
#define ADI_BMS_LATENT0_CMD_64_RDACE_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_64_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_65_RDACF_OFFSET                       844u
#define ADI_BMS_LATENT0_CMD_65_RDACF_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_65_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_66_RDSVA_OFFSET                       859u
#define ADI_BMS_LATENT0_CMD_66_RDSVA_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_66_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_67_RDSVB_OFFSET                       874u
#define ADI_BMS_LATENT0_CMD_67_RDSVB_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_67_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_68_RDSVC_OFFSET                       889u
#define ADI_BMS_LATENT0_CMD_68_RDSVC_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_68_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_69_RDSVD_OFFSET                       904u
#define ADI_BMS_LATENT0_CMD_69_RDSVD_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_69_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_70_RDSVE_OFFSET                       919u
#define ADI_BMS_LATENT0_CMD_70_RDSVE_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_70_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_71_RDSVF_OFFSET                       934u
#define ADI_BMS_LATENT0_CMD_71_RDSVF_LENGTH                       8u
#define ADI_BMS_LATENT0_CMD_71_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_72_RDSTATC_OFFSET                     949u
#define ADI_BMS_LATENT0_CMD_72_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_72_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_73_CLRFLAG_OFFSET                     964u
#define ADI_BMS_LATENT0_CMD_73_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_73_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_74_ADSV_OFFSET                        979u
#define ADI_BMS_LATENT0_CMD_74_ADSV_LENGTH                        0u
#define ADI_BMS_LATENT0_CMD_74_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_75_EMPTY_OFFSET                       984u
#define ADI_BMS_LATENT0_CMD_75_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_75_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_76_CLRFLAG_OFFSET                     991u
#define ADI_BMS_LATENT0_CMD_76_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_76_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_77_WRCFGA_OFFSET                      1006u
#define ADI_BMS_LATENT0_CMD_77_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT0_CMD_77_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT0_CMD_78_EMPTY_OFFSET                       1019u
#define ADI_BMS_LATENT0_CMD_78_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT0_CMD_78_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT0_CMD_79_CLRFLAG_OFFSET                     1026u
#define ADI_BMS_LATENT0_CMD_79_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT0_CMD_79_ENTRY_DATA_LENGTH                  8u

// Script Information: latent1
#define ADI_BMS_LATENT1_ID                                        4u
#define ADI_BMS_LATENT1_PKT_0_ID                                  9u
#define ADI_BMS_LATENT1_PKT_1_ID                                  10u

#define ADI_BMS_LATENT1_CMD_0_EMPTY_OFFSET                        5u
#define ADI_BMS_LATENT1_CMD_0_EMPTY_LENGTH                        0u
#define ADI_BMS_LATENT1_CMD_0_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT1_CMD_1_ADCV_OFFSET                         12u
#define ADI_BMS_LATENT1_CMD_1_ADCV_LENGTH                         0u
#define ADI_BMS_LATENT1_CMD_1_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT1_CMD_2_ADSV_OFFSET                         19u
#define ADI_BMS_LATENT1_CMD_2_ADSV_LENGTH                         0u
#define ADI_BMS_LATENT1_CMD_2_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT1_CMD_3_EMPTY_OFFSET                        24u
#define ADI_BMS_LATENT1_CMD_3_EMPTY_LENGTH                        0u
#define ADI_BMS_LATENT1_CMD_3_ENTRY_DATA_LENGTH                   0u
#define ADI_BMS_LATENT1_CMD_4_RDACA_OFFSET                        31u
#define ADI_BMS_LATENT1_CMD_4_RDACA_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_4_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_5_RDACB_OFFSET                        46u
#define ADI_BMS_LATENT1_CMD_5_RDACB_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_5_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_6_RDACC_OFFSET                        61u
#define ADI_BMS_LATENT1_CMD_6_RDACC_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_6_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_7_RDACD_OFFSET                        76u
#define ADI_BMS_LATENT1_CMD_7_RDACD_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_7_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_8_RDACE_OFFSET                        91u
#define ADI_BMS_LATENT1_CMD_8_RDACE_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_8_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_9_RDACF_OFFSET                        106u
#define ADI_BMS_LATENT1_CMD_9_RDACF_LENGTH                        8u
#define ADI_BMS_LATENT1_CMD_9_ENTRY_DATA_LENGTH                   8u
#define ADI_BMS_LATENT1_CMD_10_RDSVA_OFFSET                       121u
#define ADI_BMS_LATENT1_CMD_10_RDSVA_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_10_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_11_RDSVB_OFFSET                       136u
#define ADI_BMS_LATENT1_CMD_11_RDSVB_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_11_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_12_RDSVC_OFFSET                       151u
#define ADI_BMS_LATENT1_CMD_12_RDSVC_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_12_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_13_RDSVD_OFFSET                       166u
#define ADI_BMS_LATENT1_CMD_13_RDSVD_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_13_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_14_RDSVE_OFFSET                       181u
#define ADI_BMS_LATENT1_CMD_14_RDSVE_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_14_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_15_RDSVF_OFFSET                       196u
#define ADI_BMS_LATENT1_CMD_15_RDSVF_LENGTH                       8u
#define ADI_BMS_LATENT1_CMD_15_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_16_RDSTATC_OFFSET                     211u
#define ADI_BMS_LATENT1_CMD_16_RDSTATC_LENGTH                     8u
#define ADI_BMS_LATENT1_CMD_16_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_17_CLRFLAG_OFFSET                     226u
#define ADI_BMS_LATENT1_CMD_17_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT1_CMD_17_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_18_ADSV_OFFSET                        241u
#define ADI_BMS_LATENT1_CMD_18_ADSV_LENGTH                        0u
#define ADI_BMS_LATENT1_CMD_18_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT1_CMD_19_EMPTY_OFFSET                       246u
#define ADI_BMS_LATENT1_CMD_19_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT1_CMD_19_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT1_CMD_20_CLRFLAG_OFFSET                     253u
#define ADI_BMS_LATENT1_CMD_20_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT1_CMD_20_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_21_WRCFGA_OFFSET                      268u
#define ADI_BMS_LATENT1_CMD_21_WRCFGA_LENGTH                      8u
#define ADI_BMS_LATENT1_CMD_21_ENTRY_DATA_LENGTH                  8u
#define ADI_BMS_LATENT1_CMD_22_EMPTY_OFFSET                       281u
#define ADI_BMS_LATENT1_CMD_22_EMPTY_LENGTH                       0u
#define ADI_BMS_LATENT1_CMD_22_ENTRY_DATA_LENGTH                  0u
#define ADI_BMS_LATENT1_CMD_23_CLRFLAG_OFFSET                     288u
#define ADI_BMS_LATENT1_CMD_23_CLRFLAG_LENGTH                     8u
#define ADI_BMS_LATENT1_CMD_23_ENTRY_DATA_LENGTH                  8u

#define ADI_BMS_SIZE_AC1V                                         2u
#define ADI_BMS_SIZE_AC2V                                         2u
#define ADI_BMS_SIZE_AC3V                                         2u
#define ADI_BMS_SIZE_RDACA_PEC                                    2u
#define ADI_BMS_SIZE_AC4V                                         2u
#define ADI_BMS_SIZE_AC5V                                         2u
#define ADI_BMS_SIZE_AC6V                                         2u
#define ADI_BMS_SIZE_RDACB_PEC                                    2u
#define ADI_BMS_SIZE_AC7V                                         2u
#define ADI_BMS_SIZE_AC8V                                         2u
#define ADI_BMS_SIZE_AC9V                                         2u
#define ADI_BMS_SIZE_RDACC_PEC                                    2u
#define ADI_BMS_SIZE_AC10V                                        2u
#define ADI_BMS_SIZE_AC11V                                        2u
#define ADI_BMS_SIZE_AC12V                                        2u
#define ADI_BMS_SIZE_RDACD_PEC                                    2u
#define ADI_BMS_SIZE_AC13V                                        2u
#define ADI_BMS_SIZE_AC14V                                        2u
#define ADI_BMS_SIZE_AC15V                                        2u
#define ADI_BMS_SIZE_RDACE_PEC                                    2u
#define ADI_BMS_SIZE_AC16V                                        2u
#define ADI_BMS_SIZE_AC17V                                        2u
#define ADI_BMS_SIZE_AC18V                                        2u
#define ADI_BMS_SIZE_RDACF_PEC                                    2u
#define ADI_BMS_SIZE_G1V                                          2u
#define ADI_BMS_SIZE_G2V                                          2u
#define ADI_BMS_SIZE_GA11V                                        2u
#define ADI_BMS_SIZE_RDAUXA_PEC                                   2u
#define ADI_BMS_SIZE_G3V                                          2u
#define ADI_BMS_SIZE_G4V                                          2u
#define ADI_BMS_SIZE_RDAUXE_PEC                                   2u
#define ADI_BMS_SIZE_RDSTATC_PEC                                  2u
#define ADI_BMS_SIZE_PACKET_CRC                                   2u
#define ADI_BMS_SIZE_G10V                                         2u
#define ADI_BMS_SIZE_VMV                                          2u
#define ADI_BMS_SIZE_VPV                                          2u
#define ADI_BMS_SIZE_RDAUXD_PEC                                   2u
#define ADI_BMS_SIZE_S1V                                          2u
#define ADI_BMS_SIZE_S2V                                          2u
#define ADI_BMS_SIZE_S3V                                          2u
#define ADI_BMS_SIZE_RDSVA_PEC                                    2u
#define ADI_BMS_SIZE_S4V                                          2u
#define ADI_BMS_SIZE_S5V                                          2u
#define ADI_BMS_SIZE_S6V                                          2u
#define ADI_BMS_SIZE_RDSVB_PEC                                    2u
#define ADI_BMS_SIZE_S7V                                          2u
#define ADI_BMS_SIZE_S8V                                          2u
#define ADI_BMS_SIZE_S9V                                          2u
#define ADI_BMS_SIZE_RDSVC_PEC                                    2u
#define ADI_BMS_SIZE_S10V                                         2u
#define ADI_BMS_SIZE_S11V                                         2u
#define ADI_BMS_SIZE_S12V                                         2u
#define ADI_BMS_SIZE_RDSVD_PEC                                    2u
#define ADI_BMS_SIZE_S13V                                         2u
#define ADI_BMS_SIZE_S14V                                         2u
#define ADI_BMS_SIZE_S15V                                         2u
#define ADI_BMS_SIZE_RDSVE_PEC                                    2u
#define ADI_BMS_SIZE_S16V                                         2u
#define ADI_BMS_SIZE_S17V                                         2u
#define ADI_BMS_SIZE_S18V                                         2u
#define ADI_BMS_SIZE_RDSVF_PEC                                    2u
#define ADI_BMS_SIZE_RDCFGA_PEC                                   2u
#define ADI_BMS_SIZE_RDCFGB_PEC                                   2u
#define ADI_BMS_SIZE_VREF2                                        2u
#define ADI_BMS_SIZE_ITMP                                         2u
#define ADI_BMS_SIZE_RDSTATA_PEC                                  2u
#define ADI_BMS_SIZE_VD                                           2u
#define ADI_BMS_SIZE_VA                                           2u
#define ADI_BMS_SIZE_VRES                                         2u
#define ADI_BMS_SIZE_RDSTATB_PEC                                  2u
#define ADI_BMS_SIZE_R_G1V                                        2u
#define ADI_BMS_SIZE_R_G2V                                        2u
#define ADI_BMS_SIZE_R_GA11V                                      2u
#define ADI_BMS_SIZE_RDRAXA_PEC                                   2u
#define ADI_BMS_SIZE_R_G10V                                       2u
#define ADI_BMS_SIZE_R_G3V                                        2u
#define ADI_BMS_SIZE_R_G4V                                        2u
#define ADI_BMS_SIZE_RDRAXD_PEC                                   2u
#define ADI_BMS_SIZE_RDPWMA_PEC                                   2u
#define ADI_BMS_SIZE_RDSID_PEC                                    2u
#endif  /* ADI_BMS_DEFS_H_ */
